jobs:
  - job: vs2017
    displayName: Windows VS2017 Build
    timeoutInMinutes: 0
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        x86:
          PLATFORM: 'x86'
          ARCHITECTURE: 'x86'
          GENERATOR: 'Visual Studio 15 2017'
        x64:
          PLATFORM: 'x64'
          ARCHITECTURE: 'x86_amd64'
          GENERATOR: 'Visual Studio 15 2017 Win64'
    variables:
      BUILD_DIR: '$(Agent.WorkFolder)\build'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
      CONFIGURATION: 'Release'
    steps:
      - script: |
          vcpkg.exe install boost-system boost-filesystem boost-thread boost-date-time boost-iostreams boost-chrono boost-asio boost-dynamic-bitset boost-foreach boost-graph boost-interprocess boost-multi-array boost-ptr-container boost-random boost-signals2 eigen3 flann gtest qhull --triplet %PLATFORM%-windows && vcpkg.exe list
        displayName: 'Install Dependencies'
      - script: |
          rmdir %VCPKG_ROOT%\downloads /S /Q
          rmdir %VCPKG_ROOT%\packages /S /Q
        displayName: 'Free Up Space'
      - script: |
          call "%VCVARSALL%" %ARCHITECTURE%
          set PATH=%VCPKG_ROOT%\installed\%PLATFORM%-windows\bin;%PATH%
          mkdir %BUILD_DIR% && cd %BUILD_DIR%
          cmake $(Build.SourcesDirectory) -G"%GENERATOR%" -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_APPLOCAL_DEPS=ON -DPCL_BUILD_WITH_BOOST_DYNAMIC_LINKING_WIN32=ON -DPCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32=ON -DPCL_BUILD_WITH_QHULL_DYNAMIC_LINKING_WIN32=ON -DBUILD_global_tests=ON -DBUILD_tools=OFF -DBUILD_surface_on_nurbs=ON
        displayName: 'CMake Configuration'
      - script: cd %BUILD_DIR% && cmake --build . --config %CONFIGURATION%
        displayName: 'Build Library'
      - script: cd %BUILD_DIR% && ctest -C %CONFIGURATION% -V
        displayName: 'Run Unit Tests'

